/*
 * Elaastic / ElaastiX - formative assessment system
 * Copyright (C) 2019  Université de Toulouse and Université Toulouse Capitole.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

@file:Suppress("DestructuringDeclarationWithTooManyEntries")

package org.elaastix.commons.codegen.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSVisitorVoid
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.Annotatable
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.Documentable
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.toAnnotationSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import jakarta.persistence.Id
import jakarta.persistence.ManyToMany
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.OneToOne
import jakarta.persistence.Transient
import jakarta.persistence.Version
import kotlinx.serialization.Serializable
import org.elaastix.commons.codegen.AutoGeneratedCreateDto
import org.elaastix.commons.codegen.AutoGeneratedDto
import org.elaastix.commons.codegen.AutoGeneratedUpdateDto
import org.elaastix.commons.codegen.ExcludeFromDto
import org.elaastix.commons.codegen.getFilteredSymbolsWithAnnotation
import org.elaastix.commons.codegen.getKSAnnotationsByType
import org.elaastix.commons.codegen.hasAnyAnnotation

class AutoGeneratedDtoProcessor(private val codeGenerator: CodeGenerator) : SymbolProcessor {
	override fun process(resolver: Resolver): List<KSAnnotated> {
		resolver
			.getFilteredSymbolsWithAnnotation(AutoGeneratedDto::class)
			.forEach { it.accept(DtoVisitor(), Unit) }

		resolver
			.getFilteredSymbolsWithAnnotation(AutoGeneratedCreateDto::class)
		// .forEach { it.accept(createDtoVisitor, Unit) }

		resolver
			.getFilteredSymbolsWithAnnotation(AutoGeneratedUpdateDto::class)
		// .forEach { it.accept(createDtoVisitor, Unit) }

		return emptyList()
	}

	private inner class DtoVisitor : KSVisitorVoid() {
		override fun visitClassDeclaration(classDeclaration: KSClassDeclaration, data: Unit) {
			val dtoName = classDeclaration.deriveDtoName()

			val dtoCtorBuilder = FunSpec.constructorBuilder()
				.copyOptInAnnotations(classDeclaration.primaryConstructor!!)

			val dtoBuilder = TypeSpec.classBuilder(dtoName)
				.addOriginatingKSFile(classDeclaration.containingFile!!)
				.copyKdoc(classDeclaration)
				.addModifiers(KModifier.DATA)
				.addAnnotation(Serializable::class)

			val mapperBuilder = FunSpec.builder("toDto")
				.addOriginatingKSFile(classDeclaration.containingFile!!)
				.addKdoc("Maps [%1L] to [%2L].", classDeclaration, dtoName)
				.receiver(classDeclaration.toClassName())
				.returns(TypeVariableName(dtoName))

			val mapperOptIns = mutableSetOf<String>()
			val mapperBody = CodeBlock.builder()
			mapperBody.add("return $dtoName(\n")
			mapperBody.indent()

			classDeclaration.getPropertiesMapping()
				.forEach { mapping ->
					dtoCtorBuilder.addParameter(mapping.name, mapping.type)
					dtoBuilder.addProperty(
						PropertySpec.builder(mapping.name, mapping.type)
							.copyNonJpaAnnotations(mapping.property)
							.copyKdoc(mapping.property)
							.initializer(mapping.name)
							.build()
					)

					mapperOptIns.addAll(mapping.property.getOptInAnnotationArgs())
					mapperBody.add("${mapping.name} = ${mapping.entityAccessor},\n")
				}

			mapperBody.unindent()
			mapperBody.add(")")

			val dtoCtor = dtoCtorBuilder.build()
			val dto = dtoBuilder
				.primaryConstructor(dtoCtor)
				.build()

			val mapper = mapperBuilder
				.addOptIns(mapperOptIns)
				.addCode(mapperBody.build())
				.build()

			val file = FileSpec.builder(classDeclaration.deriveDtoPackageName(), dto.name!!)
				.addType(dto)
				.addFunction(mapper)
				.build()

			file.writeTo(codeGenerator, false)
		}
	}

	private fun KSClassDeclaration.getPropertiesMapping() =
		getAllProperties()
			.filterNonTransientOrSpecial()
			.filterNot { it.isRelationToMany() }
			.map { property ->
				val propertySimpleName = property.simpleName.asString()
				when {
					property.isRelationToOne() ->
						Mapping(
							MappingType.RELATION,
							property,
							propertySimpleName + "Id",
							ClassName("org.elaastix.commons.data", "Uuid"),
							"$propertySimpleName.id",
							propertySimpleName,
						)

					else ->
						Mapping(
							when {
								property.isManagedProperty() -> MappingType.MANAGED
								else -> MappingType.SIMPLE
							},
							property,
							propertySimpleName,
							property.type.toTypeName(),
							propertySimpleName,
							propertySimpleName,
						)
				}
			}

	private enum class MappingType {
		/** A simple, direct mapping of a writable type. */
		SIMPLE,
		/** Mapping to another entity. */
		RELATION,
		/** Read-only mappings handled by business logic. */
		MANAGED,
	}

	private data class Mapping(
		val mappingType: MappingType,
		val property: KSPropertyDeclaration,
		val name: String,
		val type: TypeName,
		val entityAccessor: String,
		val propertyName: String,
	)

	@Suppress("TooManyFunctions")
	companion object {
		internal fun KSClassDeclaration.deriveDtoPackageName() =
			packageName.asString().removeSuffix(".entities") + ".dto"

		internal fun KSClassDeclaration.deriveDtoName(prefix: String = "") =
			prefix + simpleName.asString().removeSuffix("Entity") + "Dto"

		internal fun Sequence<KSPropertyDeclaration>.filterNonTransientOrSpecial() = filter {
			it.validate() &&
				it.hasBackingField &&
				!it.hasAnyAnnotation(Version::class, Transient::class, ExcludeFromDto::class) &&
				it.getter?.getKSAnnotationsByType(Transient::class)?.count() == 0
		}

		internal fun Sequence<KSAnnotation>.filterNonJpa() = filter {
			val qual = it.annotationType.resolve().declaration.qualifiedName?.asString() ?: return@filter false
			qual !in arrayOf(
				"jakarta.validation.constraints.Nullable",
				"jakarta.validation.constraints.NotNull"
			) &&
				!qual.startsWith("jakarta.persistence") &&
				!qual.startsWith("org.hibernate") &&
				!qual.startsWith("org.springframework.data")
		}

		internal fun Sequence<KSAnnotation>.filterIsOrRequiresOptIn() = filter { it.isOrRequiresOptIn() }

		internal fun KSAnnotated.getOptInAnnotationArgs() = annotations.filterIsOrRequiresOptIn().flatMap {
			when {
				it.isOptIn() -> it.arguments.map { a -> a.value.toString() }
				else -> setOf("${it.shortName.asString()}::class")
			}
		}

		internal fun KSPropertyDeclaration.isManagedProperty() =
			simpleName.getShortName() in arrayOf("id", "updatedAt", "author", "owner") || hasAnyAnnotation(Id::class)

		internal fun KSPropertyDeclaration.isRelationToOne() =
			hasAnyAnnotation(OneToOne::class, ManyToOne::class)

		internal fun KSPropertyDeclaration.isRelationToMany() =
			hasAnyAnnotation(OneToMany::class, ManyToMany::class)

		internal fun <T : Documentable.Builder<*>> T.copyKdoc(from: KSDeclaration) = also {
			from.docString?.let { addKdoc(it.trimIndent()) }
		}

		internal fun <T : Annotatable.Builder<*>> T.copyNonJpaAnnotations(from: KSAnnotated) = also {
			from.annotations.filterNonJpa().forEach { addAnnotation(it.toAnnotationSpec(omitDefaultValues = true)) }
		}

		internal fun <T : Annotatable.Builder<*>> T.copyOptInAnnotations(from: KSAnnotated) = also {
			from.annotations.filterIsOrRequiresOptIn().forEach { addAnnotation(it.toAnnotationSpec(omitDefaultValues = true)) }
		}

		internal fun <T : Annotatable.Builder<*>> T.addOptIns(optIns: Iterable<String>) = also {
			var added = false
			val annotation =
				AnnotationSpec.builder(ClassName("kotlin", "OptIn"))
				.apply { optIns.forEach { added = true; addMember(it) } }
				.build()

			if (added) addAnnotation(annotation)
		}

		internal fun KSAnnotation.isOptIn(): Boolean =
			shortName.asString() == "OptIn"

		internal fun KSAnnotation.isOrRequiresOptIn(): Boolean =
			isOptIn() || annotationType.resolve().declaration.annotations.any {
				it.shortName.asString() == "RequiresOptIn" ||
					// Target and Retention are applied on themselves. Whoops!
					(it.shortName.asString() !in arrayOf("Target", "Retention") && it.isOrRequiresOptIn())
			}
	}
}
