shamefullyHoist: true
blockExoticSubdeps: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3  # https://github.com/paulmillr/chokidar/issues/1440
  - semver@5.7.2 || 6.3.1  # Old versions, published while attestation was a new feature
