services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: elaastix
      POSTGRES_PASSWORD: elaastix
      POSTGRES_DATABASE: elaastix
    healthcheck:
      # noinspection SpellCheckingInspection
      test: [ "CMD", "pg_isready",  "-U", "elaastix" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:5432:5432"
    read_only: true
    volumes:
      - pg-data:/var/lib/postgresql
    tmpfs:
      - /run/postgresql
      - /tmp

  storage:
    image: dxflrs/garage:v2.1.0
    read_only: true
    volumes:
      - .config/garage/config.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    tmpfs:
      - /tmp

  server:
    pull_policy: never
    image: elaastic/elaastix-server:local-develop
    build:
      context: .
      dockerfile: server/Containerfile
      target: develop
    env_file:
      - .config/garage/credentials.env
    environment:
      SPRING_PROFILES_ACTIVE: develop,container
    command: bootRunDebug
    ports:
      - "127.0.0.1:20177:20177"
      - "127.0.0.1:8080:8080"
    read_only: false  # Gradle is too write-heavy to restrict the filesystem, unfortunately.
    volumes:
      - gradle-cache:/root/.gradle
      # Gradle config
      - ./gradle:/work/gradle:ro
      - ./gradle.properties:/work/gradle.properties:ro
      - ./settings.gradle.kts:/work/settings.gradle.kts:ro
      - ./build.gradle.kts:/work/build.gradle.kts:ro
      # frontend (cfg only)
      - ./frontend/build.gradle.kts:/work/frontend/build.gradle.kts:ro
      # build-logic
      - ./build-logic/settings.gradle.kts:/work/build-logic/settings.gradle.kts:ro
      - ./build-logic/build.gradle.kts:/work/build-logic/build.gradle.kts:ro
      - ./build-logic/src:/work/build-logic/src:ro
      # server
      - ./server/build.gradle.kts:/work/server/build.gradle.kts:ro
      - ./server/src:/work/server/src:ro
      # commons
      - ./commons/build.gradle.kts:/work/commons/build.gradle.kts:ro
      - ./commons/src:/work/commons/src:ro
      # metamodel
      - ./metamodel/build.gradle.kts:/work/metamodel/build.gradle.kts:ro
      - ./metamodel/src:/work/metamodel/src:ro
    tmpfs:
      - /tmp
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
  garage-meta:
  garage-data:
  gradle-cache:
