#!/usr/bin/env -S just --justfile

set guards

_default:
	just --list

[group('validate')]
[doc('Checks that modified files are correctly formatted and/or pass linter tests.')]
check:
	hk check

[group('validate')]
[doc('Reformats and auto-fixes lint issues (when possible) in modified files.')]
fix:
	hk fix

[group('validate')]
[doc('Same as `check`, but for all files (not just modified ones).')]
check-all:
	hk check --all

[group('validate')]
[doc('Same as `fix`, but for all files (not just modified ones).')]
fix-all:
	hk fix --all

[group('run')]
[doc('Start sidecar services (Database, S3, etc...). Will wait for them to be healthy.')]
sidecar:
	docker compose up -d --wait postgres storage

[group('run')]
[doc('Start everything up, opening a tmux session for observing and managing all running services.')]
start:
	docker compose up --build -d
	mise x tmux -- tmux new-session -d -s elaastix \; \
		new-window -c 'frontend' -n 'Frontend' 'pnpm run dev; $SHELL' \; \
		new-window -n 'Backend' 'docker compose attach server; $SHELL' \; \
		new-window -n 'Postgres' 'docker compose attach postgres; $SHELL' \; \
		new-window -n 'Garage' 'docker compose attach storage; $SHELL' \; \
		select-window -t:0 \; \
		setw -g mouse on \; \
		attach

[group('run')]
[doc('Stops everything, and kills the tmux session.')]
stop:
	docker compose stop
	-mise x tmux -- tmux kill-session -t elaastix

[group('build')]
[doc('Generates the OpenAPI 3.1 configuration spec file.')]
@openapi:
	?[ "${SKIP_OPENAPI_GENERATION:-}" != "true" ]
	-rm server/build/openapi.json 2>/dev/null
	just sidecar gradle :server:bootRun --args=\"--spring.profiles.active=develop,openapi\"
	test -f server/build/openapi.json

[group('dependencies')]
[doc('Checks for Gradle dependency updates.')]
gradle-check-updates *ARGS: && (gradle "dependencyUpdates" "--no-configuration-cache" "--no-parallel" ARGS)

[group('misc')]
[doc('Cleans the repository to its original state. Will erase local configuration (e.g. mise.local.toml), but preserve the IJ shelf.')]
[confirm('This action WILL ERASE ALL LOCAL CONFIGS AND UNTRACKED FILES. IJ shelves will be preserved. Continue? [y/N]')]
clean:
	docker compose down --remove-orphans -v
	git clean -xdf --exclude .idea/shelf

[group('misc')]
[doc('Removes the PostgreSQL database and the files stored in Garage.')]
[confirm('The database contents and the files stored in S3 will be permanently removed. Continue? [y/N]')]
purge-db:
	docker compose down postgres storage -v

[group('misc')]
[doc('Lists all files that would be cleaned by the clean task.')]
clean-dry:
	git clean --dry-run -xdf --exclude .idea/shelf

[windows]
[group('misc')]
[doc('Runs a gradle command. OS-independent helper')]
[no-exit-message]
@gradle *ARGS:
	./gradlew.bat {{ARGS}}

[unix]
[group('misc')]
[doc('Runs a gradle command. OS-independent helper')]
[no-exit-message]
@gradle *ARGS:
	./gradlew {{ARGS}}

[group('misc')]
[doc('Deletes all temporary files generated by IntelliJ. Workaround for IJ bug on WSL: IDEA-384441')]
[confirm('This workaround will aggressively remove temporary files and may disrupt other processes. Proceed?')]
ij-wsl-clear:
	rm /tmp/**/*.jar /tmp/**/*.gradle >/dev/null 2>&1 || true
	rmdir /tmp/* >/dev/null 2>&1 || true
