packages:
  - frontend

allowBuilds:
  "@parcel/watcher": true
  cbor-extract: false
  esbuild: true
  sharp: false
  unrs-resolver: false
  vue-demi: false

trustPolicyExclude:
  - chokidar@4.0.3 # https://github.com/paulmillr/chokidar/issues/1440
  - semver@5.7.2 || 6.3.1 # Old versions, published while attestation was a new feature

overrides:
  vite: ^7

pmOnFail: error

patchedDependencies:
  '@nuxt/fonts': patches/@nuxt__fonts.patch
  temml: patches/temml.patch
