packages:
  - frontend

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: false
  unrs-resolver: false
  vue-demi: false

trustPolicyExclude:
  - chokidar@4.0.3  # https://github.com/paulmillr/chokidar/issues/1440
  - semver@5.7.2 || 6.3.1  # Old versions, published while attestation was a new feature

overrides:
  vite: ^8

pmOnFail: error
