debug: true
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/elaastix
    username: elaastix
    password: elaastix

springdoc.paths-to-exclude: []
springdoc.cache.disabled: true

# Disable OpenTelemetry in development
management:
  otlp.metrics.export.enabled: false
  logging.export.otlp.enabled: false
  tracing.export.otlp.enabled: false

scalar:
  authentication: # noinspection SpringBootApplicationYaml
    preferred-security-scheme: Token
    api-key: # noinspection SpringBootApplicationYaml
      Token:
        value: Develop 00000000-0000-0000-0000-000000000001

elaastix:
  security:
    cookie-secure: false
    encryption-key: super duper strong password (it's very strong)
    authn:
      develop: true
