@startuml(id=Subject)
'https://plantuml.com/class-diagram


!include ../../../../user/api/user.puml
!include ../topic/topic.puml

class Subject {
    id: UUID
    ownerId: UUID
    topicId: UUID
    version: Long
    title: String
    description: String
    lastUpdated: ZoneDateTime
}

Subject "*" -> "1" User : owned by
Subject "*" -> "0..1" Topic : relative to
@enduml
