@startuml
'https://plantuml.com/class-diagram

!include ../user.puml
!include ../activity-metamodel.puml

package activity.feedback {
    class GetFeedbackActivitySession extends activity.metamodel.ActivitySession {
        learner: Learner
    }

    GetFeedbackActivitySession --> Learner
}

@enduml
