@startuml(id=User)
'https://plantuml.com/class-diagram

class User
class Learner extends User
class Teacher extends User

interface Cohort {
    users: Set<User>
}

class LearnerCohort implements Cohort
class TeacherCohort implements Cohort

Cohort "*" *-- "*" User : belongs to <

User "1" -- "0..1" UserAccount

@enduml
