@startuml
'https://plantuml.com/class-diagram

package metamodel.activity {
	interface AbsoluteGradable {
		+absoluteGrade: AbsoluteGrade
	}

	interface ScalarGradable {
		+scalarGrade: ScalarGrade
	}

	enum AbsoluteGrade {
		INCORRECT,
		CORRECT,
		PARTIAL,
		NEUTRAL,
	}

	class ScalarGrade <<embeddable>> {
		value: BigDecimal
		max: BigDecimal
	}
}

@enduml
