/*
 * Elaastic / ElaastiX - formative assessment system
 * Copyright (C) 2019  Université de Toulouse and Université Toulouse Capitole.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.elaastix.server.sequences

import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.ManyToOne
import jakarta.validation.constraints.Size
import org.elaastix.commons.codegen.AutoGeneratedCreateDto
import org.elaastix.commons.codegen.AutoGeneratedDto
import org.elaastix.commons.codegen.AutoGeneratedUpdateDto
import org.elaastix.commons.jpa.entity.AbstractEntity
import org.elaastix.commons.platform.SciconumOnly
import org.elaastix.commons.platform.UnclearAuthorshipOwnership
import org.elaastix.server.activities.response.entities.QuestionEntity
import org.elaastix.server.scenario.SciconumScenario
import org.elaastix.server.users.entities.UserEntity
import org.springframework.data.annotation.CreatedBy

/**
 * A pedagogical sequence.
 * TODO: Extensive description of the concept.
 */
@Entity
@AutoGeneratedDto
@AutoGeneratedCreateDto
@AutoGeneratedUpdateDto
class SequenceEntity @SciconumOnly constructor(
	/**
	 * Display name of the sequence.
	 */
	@Size(min = 2, max = 64)
	var name: String,

	/**
	 * SCICONUM scenario of the sequence.
	 */
	@property:SciconumOnly
	@Enumerated(EnumType.STRING)
	var sciconumScenario: SciconumScenario,

	/**
	 * Question for the SCICONUM sequence.
	 */
	@property:SciconumOnly
	@ManyToOne(fetch = FetchType.EAGER)
	var sciconumQuestion: QuestionEntity,
) : AbstractEntity() {
	/**
	 * Owner of the resource, but not necessarily its author per se.
	 */
	@property:UnclearAuthorshipOwnership
	@ManyToOne(fetch = FetchType.LAZY)
	@CreatedBy
	lateinit var owner: UserEntity
}
