FROM eclipse-temurin:25-jdk-alpine AS base

WORKDIR /build

# Copy core project files
COPY gradle/ ./gradle/
COPY build-logic/ ./build-logic/
COPY frontend/*.gradle.kts ./frontend/
COPY server/*.gradle.kts ./server/
COPY *.gradle.kts *.gradle gradle.properties gradlew ./

# Make Gradle download dependencies (and build `build-logic`) prior to copying sources.
# This makes better use of Docker's cache system. We can't use cache mounts as dev image needs libs at runtime.
RUN ./gradlew --no-daemon :server:classes :server:resolveDependencies

# Will be used by the development containers
COPY server/docker-entrypoint.sh ./server/
ENTRYPOINT [ "/build/server/docker-entrypoint.sh" ]

FROM base AS build

COPY server/ ./server/
RUN ./gradlew --offline --no-daemon :server:bootJar -x test

# Having a jar file in a container is unfortunate: both are effectively archive formats... Russian dolls!
# Spring has a feature to extract the fat jar into a layered unpacked structure that's ideal for containers
RUN java -Djarmode=tools -jar server/build/libs/*-boot.jar extract --launcher --layers --destination server/build/extracted

FROM eclipse-temurin:25-jre-alpine

ENV SPRING_PROFILES_DEFAULT=container

WORKDIR /app

# The order is important and allows better reuse of layers. Order recommended by Spring.
COPY --from=build /build/server/build/extracted/dependencies/ ./
COPY --from=build /build/server/build/extracted/spring-boot-loader/ ./
COPY --from=build /build/server/build/extracted/snapshot-dependencies/ ./
COPY --from=build /build/server/build/extracted/application/ ./

HEALTHCHECK --interval=1m --timeout=3s CMD wget --spider http://localhost:3000 || exit 1

ENTRYPOINT [ \
    "java", \
    "-Xms512M", "-Xmx2048M", \
    "-server", "-XX:+UseParallelGC", \
    "-Djava.security.egd=file:/dev/./urandom", \
    "-Djava.io.tmpdir=/tmp/", \
    "org.springframework.boot.loader.launch.JarLauncher" \
]
