#:schema taplo://taplo.toml

exclude = ["**/node_modules/**", "**/target/**"]

[formatting]
indent_string = "\t"


[[rule]]
include = ["gradle/libs.versions.toml"]

[rule.formatting]
reorder_keys = true
