@startuml
'https://plantuml.com/class-diagram

class User
class UserGroup {
    users: Collection<User>
}

UserGroup *-- User : belongs to <

class Assignment {
    teachers: Collection<User | UserGroup>
    learners: Collection<User | UserGroup>
    sequences: List<Sequence>
}
note top
An assignment contains a list of learning sequence.
An assignment is managed by users registered as teachers.
An assignment is played by users registered as learners.
end note

Assignment "*" *- "*" User : registered as learner <
Assignment "*" *- "*" User : registered as teacher <
Assignment "*" *- "*" UserGroup : registered as learner <
Assignment "*" *- "*" UserGroup : registered as teacher <

Assignment *- activity.metamodel.Sequence : contains >

package activity.metamodel {
    abstract class Scenario
    note top
    The scenario is responsible for creating and updating ActivitySession.
    It will react to sequence updates and activity sessions events.
    end note

    class Sequence {
        state: State
        scenario: Scenario
        start()
        pause()
        resume()
        stop()
    }

    enum State {
        OPEN
        PENDING
        RUNNING
        CLOSED
    }

    Sequence --> State
    Sequence --> activity.metamodel.Scenario

    Scenario *- ActivitySession : Managed by <

    abstract class ActivitySession {
        context: Sequence
        activityConfig: ActivityConfig
        state: State
        activityCompleted: boolean
        abstract getLearners(): Collection<User>
        abstract getInputMaterial(): Collection<Material>
        abstract getLearnerOutput(): Collection<LearnerOutput>
    }

    class ActivitySessionLog

    ActivitySession --> State
    ActivitySession --> ActivitySessionLog
    ActivitySession --> ActivityConfig
    ActivitySession *-- LearnerOutput
    ActivitySession *-- Material


    interface ActivityConfig

    interface Material

    abstract class LearnerOutput extends Material {
        author: User
    }

    LearnerOutput -- User : Produced by >
}

class ManualScenario extends activity.metamodel.Scenario {
    createActivitySession()
    startActivitySession(sessionId)
    closeActivitySession(sessionId)
}

abstract class NPhaseScenario extends activity.metamodel.Scenario

class AsynchronousNPhaseScenario extends NPhaseScenario
class SynchronousNPhaseScenario extends NPhaseScenario

class ControlGroup1Scenario extends activity.metamodel.Scenario {
    question: Question
    responseToJudge1: activity.response.Response
    responseToJudge2: activity.response.Response

    run()
}

ControlGroup1Scenario --> activity.response.Question
ControlGroup1Scenario --> activity.response.Response

package activity.response {
    class ResponseActivitySession extends activity.metamodel.ActivitySession {
        learner: User
        activityConfig: ResponseActivityConfig
        material: Question
        output: Response

        submitResponse()
    }

    class ChangeResponseActivitySession extends ResponseActivitySession {
        previousResponse: Response
        modifyResponse()
    }

    ResponseActivitySession --> User
    ResponseActivitySession --> Response
    ResponseActivitySession --> ResponseActivityConfig

    class ResponseActivityConfig implements activity.metamodel.ActivityConfig {
        provideConfidenceDegree: boolean
        provideExplanation: boolean
    }

    class Question implements activity.metamodel.Material {
        statement: String
        choices: List<Choice>
        correctionChoice: Choice
        explanatoryFeedback: String
    }

    class Response implements activity.metamodel.LearnerOutput {
        question: Question
        choice
        confidenceDegree
        explanation
    }

    Response --> Question
    Response --> User
}

package activity.judge {
    class JudgeActivitySession extends activity.metamodel.ActivitySession {
        learner: User
        activityConfig: ActivityConfig
        material: Collection<Material>
    }

    class JudgeActivityConfig extends activity.metamodel.ActivityConfig {

    }

    JudgeActivitySession --> User
    JudgeActivitySession --> JudgeActivityConfig
    JudgeActivitySession *-- Judgement
    JudgeActivitySession *-- activity.metamodel.Material

    class Judgement implements activity.metamodel.LearnerOutput {
        material: activity.metamodel.Material
        judgement

    }
    Judgement --> activity.metamodel.Material

}

package activity.chat {
    class ChatActivitySession extends activity.metamodel.ActivitySession {
        learners: Collection<User>
        topic: Material
    }

    ChatActivitySession *-- User
    ChatActivitySession --> activity.metamodel.Material
}

package activity.feedback {
    class GetFeedbackActivitySession extends activity.metamodel.ActivitySession {
        learner: User
    }

    GetFeedbackActivitySession --> User
}

package activity.generic {
    class WaitActivitySession extends activity.metamodel.ActivitySession
}
note top
A WaitActivitySession is used to make learners wait for an event to happen
before they can proceed to the next activity in the sequence.
end note
@enduml
