name: Lint

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  typos:
    name: Typos
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: typos -c .config/typos/config.toml

  toml:
    name: TOML
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: taplo format --check
      - run: taplo lint

  actionlint:
    name: GitHub Actions
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: actionlint

  kotlin:
    name: Kotlin lint
    timeout-minutes: 60
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew detekt

      - name: Upload SARIF report to GitHub CodeQL
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

  js-lint:
    name: JavaScript lint
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - run: pnpm i --frozen-lockfile
        working-directory: frontend

      # setup-node configures an eslint problem matcher ootb
      - run: pnpm run lint
        working-directory: frontend

  js-typecheck:
    name: JavaScript typechecking
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - run: pnpm i --frozen-lockfile
        working-directory: frontend
      # setup-node configures a tsc problem matcher ootb
      - run: pnpm run typecheck
        working-directory: frontend
