#:schema https://mise.jdx.dev/schema/mise.json
min_version = "2026.4.18" # Required: `mise prepare` renamed to `mise deps`

[settings]
experimental = true

[tools]
actionlint = "latest"
hk = "latest"
java = "temurin-25"
jq = "latest"
just = "latest"
node = { version = "24", postinstall = "corepack enable" }
pkl = "latest"
taplo = "latest"
typos = "latest"
zizmor = "latest"

[deps.pnpm]
sources = ["pnpm-workspace.yaml", "pnpm-lock.yaml", "frontend/package.json"]
outputs = ["node_modules", "frontend/node_modules"]

[deps.garage]
sources = ["compose.yaml", ".config/garage/configure.sh"]
outputs = [".config/garage/credentials.env"]
run = "sh .config/garage/configure.sh"

[deps.hk]
sources = [".config/mise/config.toml", ".config/hk.pkl"]
outputs = [".git/hooks/pre-commit", ".git/hooks/commit-msg"]
# Even with the Mise plugin, IJ fails to locate `mise` because of bad PATH...
run = "hk install --mise && find '.git/hooks' -type f -exec sed -i \"s|mise x|$(which mise) x|\" {} ';'"

[shell_alias]
eslint = "pnpm eslint"
garage = "docker compose exec -it storage /garage"
psql = "docker compose exec -it postgres psql -U elaastix"
typos = "typos --config {{config_root}}/.config/typos/config.toml"

[env]
NODE_ENV = "development"
POSTGRES_PASSWORD = "elaastix"
POSTGRES_USER = "elaastix"
TAPLO_CONFIG = "{{config_root}}/.config/taplo.toml"
